#!/usr/bin/env python
# encoding: utf-8

from waflib import Utils

def configure(ctx):
    print("Configure from: " + ctx.path.abspath())

def build(ctx):
    print("Build from: " + ctx.path.abspath())

    import os
    import os.path
    import re

    abspath = ctx.path.abspath()
    lib = os.path.basename(abspath)
    install_dir = "${DATADIR}/" +  lib
    prj = "src"

    src = [ "adpcm.c" ]
    print lib, src
    src = [os.path.join(prj,f) for f in src]
    ctx.stlib(features='c cstlib', target=lib, source=src)

    name = "rawcaudio.x"
    src = [ "rawcaudio.c" ]
    src = [os.path.join(prj,f) for f in src]
    task = ctx(features='c cprogram', target=name, source=src, use=[lib])
    task.install_path = install_dir
    task.chmod = Utils.O755

    name = "rawdaudio.x"
    src = [ "rawdaudio.c" ]
    src = [os.path.join(prj,f) for f in src]
    task = ctx(features='c cprogram', target=name, source=src, use=[lib])
    task.install_path = install_dir
    task.chmod = Utils.O755


    #ctx.install_files(install_dir, ['config.tsv', 'base_output'])
    #ctx.install_files(install_dir, [f for f in os.listdir(abspath) if re.match(r'input_.*$', f)])
    #ctx.install_files(install_dir, ['check', 'progress'], chmod=Utils.O755)

	


